type: object
required:
 - provider
 - owner
 - name
 - url
 - root_path
properties:
  url:
    type: string
    description: application git repository URL
    example: https://github.com/Qovery/simple-node-app
  branch:
    type: string
    description: |
      Name of the branch to use. This is optional
      If not specified, then the branch used is the `main` or `master` one
    example: feat/text_xxx
  root_path:
    type: string
    default: /
    description: indicates the root path of the application.