name: Update Documentation

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_DOCUMENTATION }}

      - name: Clone target repository
        run: |
          git clone git@github.com:Qovery/documentation-v2.git documentation

      - name: Copy file and push
        run: |
          cp openapi.yaml documentation/docs/api-reference/openapi.yaml
          cd documentation
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update openapi spec" -m "https://github.com/Qovery/qovery-openapi-spec/blob/main/.github/workflows/update_documentation.yaml" || echo "No changes to commit"
          git push origin main
